name: push_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  change_app_package_name: ^1.3.0
  equatable: ^2.0.5
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
